### ISSUE TITLE
Packages should be pre-installed

### ISSUE THREAD

**Issue by codetheorem** [vitejs/create-vite-app#42]
All the NPM packages required should be installed by the CLI itself rather than manual installation. It should be ready to use as one creates a new app using this CLI.

**Comment by yyx990803** [comment]
The main issue is that users may have different package manager preferences (npm, yarn, yarn 2, pnpm...). We'd need to detect what are installed on the user's system, select the correct ones and handle all kind of issues (I know this because I did it in vue-cli). This tool aims to be as lightweight as possible without getting into unnecessary maintenance burden.

In addition, there are cases where I explicitly don't want to install the dependencies, because I have them globally linked already for debugging.

Typing the command yourself really isn't that much work.
