### ISSUE TITLE
Add Typescript option during "npm init vite-app" like vue-cli

### ISSUE THREAD

**Issue by softboy99** [vitejs/create-vite-app#58]
please add Typescript option during "npm init vite-app" like vue-cli. Thanks a lot

**Comment by yyx990803** [comment]
There's currently a `vue-ts` template but is highly experimental: `npm init vite-app -- -t vue-ts`

**Comment by djasnowski** [comment]
> There's currently a `vue-ts` template but is highly experimental: `npm init vite-app -- -t vue-ts`

(Not sure what I'm doing wrong but this creates a folder `-t` on my Ubuntu 20.04) 

Would you, instead, recommend doing `vue add typescript`? I suppose, it seems, that Babel would then take over instead of vite... Hmm. I am guessing TypeScript and Vue 3 are not yet ready for the limelight as you mentioned.
